apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: three-tier-app
type: Opaque
data:
  jwt-secret: Y2hhbmdlX3RoaXNfdG9fYV92ZXJ5X3N0cm9uZ19zZWNyZXRfa2V5  # change_this_to_a_very_strong_secret_key
