apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: three-tier-app
type: Opaque
data:
  root-username: YWRtaW4=  # admin
  root-password: Y2hhbmdlX3RoaXNfc3Ryb25nX3Bhc3N3b3Jk  # change_this_strong_password
